# Generated by Django 2.1.4 on 2018-12-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='author_set',
            field=models.ManyToManyField(null=True, to='index.Author'),
        ),
    ]
