# Generated by Django 2.1.4 on 2018-12-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
        ('memberapp', '0002_auto_20181224_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='cart_count', verbose_name='数量')),
                ('good', models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'cartinfo',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNO', models.CharField(max_length=30, verbose_name='订单编号')),
                ('acot', models.CharField(max_length=200, verbose_name='数量')),
                ('aprice', models.CharField(max_length=200, verbose_name='价格')),
                ('ads', models.CharField(max_length=200, verbose_name='收件人')),
                ('cals', models.TextField(blank=True, null=True, verbose_name='订单详情')),
                ('orderStatus', models.IntegerField(blank=True, choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
    ]
