# Generated by Django 2.1.4 on 2018-12-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价钱')),
                ('unit', models.CharField(default='元', max_length=20, verbose_name='单位')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/good', verbose_name='照片')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('detail', models.TextField(max_length=1000, verbose_name='详情')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/good_type', verbose_name='照片')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsType'),
        ),
    ]
