# Generated by Django 2.1.4 on 2019-01-21 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('logo', models.ImageField(default='', upload_to='img/logo', verbose_name='logo')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '品牌信息',
                'verbose_name_plural': '品牌信息',
            },
        ),
        migrations.CreateModel(
            name='CarImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='img/car', verbose_name='封面图片')),
                ('img2', models.ImageField(upload_to='img/car', verbose_name='细节图片1')),
                ('img3', models.ImageField(upload_to='img/car', verbose_name='细节图片2')),
                ('img4', models.ImageField(upload_to='img/car', verbose_name='细节图片3')),
                ('img5', models.ImageField(upload_to='img/car', verbose_name='细节图片4')),
                ('img6', models.ImageField(upload_to='img/car', verbose_name='细节图片5')),
            ],
            options={
                'verbose_name': '汽车图片',
                'verbose_name_plural': '汽车图片',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=200, verbose_name='型号')),
                ('color', models.IntegerField(choices=[(0, '黑色'), (1, '白色'), (2, '红色'), (3, '蓝色'), (4, '银灰色'), (5, '紫色')], default=0, verbose_name='颜色')),
                ('regist_data', models.DateField(verbose_name='上牌日期')),
                ('mileage', models.IntegerField(verbose_name='公里数')),
                ('car_type', models.IntegerField(choices=[(0, '小型车'), (1, '紧凑经济型'), (2, '中型'), (3, '中大型车'), (4, '豪华车')], default=1, verbose_name='车型')),
                ('place', models.CharField(max_length=200, verbose_name='上牌地')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='期望成交价格')),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='新车价格')),
                ('effluent_standard', models.IntegerField(choices=[(0, '国一'), (1, '国二'), (2, '国三'), (3, '国四'), (4, '国五'), (5, '国六')], default=4, verbose_name='排放标准')),
                ('content', models.TextField(verbose_name='汽车详情')),
                ('created_updated_time', models.DateTimeField(auto_now=True, verbose_name='汽车上架时间')),
                ('isLegal', models.BooleanField(default=False, verbose_name='是否为盗抢查封')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否已经售出')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.Brand', verbose_name='汽车品牌')),
            ],
            options={
                'verbose_name': '汽车信息',
                'verbose_name_plural': '汽车信息',
            },
        ),
        migrations.AddField(
            model_name='carimg',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.CarInfo', verbose_name='汽车型号'),
        ),
    ]
