# Generated by Django 2.1.4 on 2019-01-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='isDelete',
            field=models.BooleanField(default=True, verbose_name='是否在售'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='isLegal',
            field=models.BooleanField(default=True, verbose_name='是否不为盗抢查封车'),
        ),
    ]
