# Generated by Django 2.1.4 on 2019-01-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_auto_20190121_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='isDelete',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
