# Generated by Django 2.1.4 on 2019-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_auto_20190121_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimg',
            name='isDelete',
            field=models.BooleanField(default=True, verbose_name='是否保存图片信息'),
        ),
    ]
