"""empty message

Revision ID: 618a865ea380
Revises: 
Create Date: 2018-12-12 20:10:29.037022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a865ea380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pname')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phonenumber', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_table('citys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=80), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citys')
    op.drop_table('users')
    op.drop_table('provinces')
    # ### end Alembic commands ###
